import React from "react";

export default function TermsAndConditions() {
  return (
    <main className="container mx-auto max-w-3xl px-6 py-12 bg-white rounded-xl shadow-lg mt-10 mb-10">
      <h1 className="text-4xl font-bold text-primary mb-8">Privacy Policy for IMF Grant</h1>

      <p className="text-base text-gray-700 leading-relaxed mb-6">
        At IMF Grant, we are committed to protecting your privacy. This Privacy Policy outlines how we collect, use, and safeguard your information when you visit our website. By using our site, you agree to the terms of this policy.
      </p>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-primary mb-2">Interpretation and Definitions</h2>
        <h2 className="text-2xl font-semibold text-primary mb-2">1. Interpretation</h2>
        <p className="text-base text-gray-700 leading-relaxed">
            The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-primary mb-2">3. Definitions</h2>
        <p className="text-base text-gray-700 leading-relaxed">
          For the purposes of these Terms & Conditions:
        </p>
        <ul className="list-disc list-inside mt-2 text-gray-700">
          <li className="mb-2"><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li className="mb-2"><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
          <li className="mb-2"><strong>Country</strong> refers to: New York, United States</li>
          <li className="mb-2"><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to IMF Grant.</li>
          <li className="mb-2"><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
          <li className="mb-2"><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
          <li className="mb-2"><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
          <li className="mb-2"><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
          <li className="mb-2"><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          <li className="mb-2"><strong>Website</strong> refers to IMF Grant, accessible from <a href="https://imfgrant.com" className="text-blue-500 underline">https://imfgrant.com</a></li>
          <li className="mb-2"><strong>Service</strong> refers to the Website.</li>
          <li className="mb-2"><strong>Terms and Conditions</strong> (also referred as "Terms") mean these Terms and Conditions that form the entire agreement between You and the Company regarding the use of the Service.</li>
          <li className="mb-2"><strong>Third-party Social Media Service</strong> means any services or content (including data, information, products or services) provided by a third-party that may be displayed, included or made available by the Service.</li>
        </ul>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-primary mb-2">4. Collecting and Using Your Personal Data</h2>
        <h2 className="text-2xl font-semibold text-primary mb-2">Types of Data Collected</h2>
        <h2 className="text-2xl font-semibold text-primary mb-2">Personal Data</h2>
        <p className="text-base text-gray-700 leading-relaxed">
          While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to: Email address, First name and last name, Phone number, Address, State, Province, ZIP/Postal code, City, Usage Data.
        </p>

        <h2 className="text-2xl font-semibold text-primary mb-2">Usage Data</h2>
        <p className="text-base text-gray-700 leading-relaxed">
          While using Our Service, We may collect Usage Data, which is information that your browser sends whenever you visit our Service or when you access the Service by or through any device ("Usage Data"). This Usage Data may include information such as your computer's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
          <br /><br />
          When you access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device you use, your mobile device unique ID, the IP address of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-primary mb-2">4. Use of Your Personal Data</h2>
        <p className="text-base text-gray-700 leading-relaxed">
          The Company may use Personal Data for the following purposes: To provide and maintain our Service, including to monitor the usage of our Service. To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user. For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service. To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation. To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information. To manage Your requests: To attend and manage Your requests to Us.
        </p>
      </section>
      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-primary mb-2">5. Links to Other Websites</h2>
        <p className="text-base text-gray-700 leading-relaxed">
          Our Service may contain links to third-party web sites or services that are not owned or controlled by the Company.

          The Company has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party web sites or services. You further acknowledge and agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods or services available on or through any such web sites or services.

          We strongly advise You to read the terms and conditions and privacy policies of any third-party web sites or services that You visit.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-primary mb-2">6. Security of Your Personal Data</h2>
        <p className="text-base text-gray-700 leading-relaxed">
          The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.

          We will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-primary mb-2">7. Changes to Terms</h2>
        <p className="text-base text-gray-700 leading-relaxed">
          We reserve the right to update these terms at any time. Continued use of the site means you accept the new terms.
        </p>
      </section>

      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-primary mb-2">8. Contact Us</h2>
        <p className="text-base text-gray-700 leading-relaxed">
          If you have any questions about these Terms & Conditions, please contact us at support@imfgrant.org
        </p>
      </section>

      <footer className="pt-8 border-t mt-8 text-center text-gray-400 text-sm">
        &copy; {new Date().getFullYear()} IMF Grant. All rights reserved.
      </footer>
    </main>
  );
}